sudo: required
os:
- linux
- osx

language: generic

install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo brew update          ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo brew install octave;   fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-add-repository -y ppa:octave/stable; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq                     ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq octave             ; fi

env:
  global:
    - SEARCH_PATH=$TRAVIS_BUILD_DIR/docs

script:
- octave-cli --no-gui -p $SEARCH_PATH --eval ver
