sudo: required
dist: xenial
# dist: trusty
# dist: precision # octave 3.2.4

addons:
  apt:
    sources:
    - sourceline: 'ppa:octave/stable'   ## without this, it's octave 4.0.0
    packages:
    - octave        # octave 4.2.2
    update: true
  homebrew:
    packages:
    - octave        # octave 4.4.1
    update: true
os:
- linux
- osx

language: generic

# install:
# - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rm '/usr/local/include/c++'; fi
# - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update                ; fi
# - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install octave        ; fi
# # - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-add-repository -y ppa:octave/stable; fi
# # - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq                     ; fi
# # - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq octave             ; fi

env:
  global:
    - SEARCH_PATH=$TRAVIS_BUILD_DIR/docs

script:
- octave --no-gui -p $SEARCH_PATH --eval ver
- octave --no-gui -p $SEARCH_PATH --eval exit(1)
