sudo: required
dist: xenial

language: generic

install:
- sudo apt-add-repository -y ppa:octave/stable
- sudo apt-get update -qq
- sudo apt-get install -qq octave

env:
  global:
    - SEARCH_PATH=$TRAVIS_BUILD_DIR/docs

script:
- octave-cli --no-gui -p $SEARCH_PATH --eval ver
