sudo: required

# addons:
#   homebrew:
#     packages:
#     - ipopt
#     - octave        # octave 5.1.0
#     update: true
os:
- osx

language: generic

install:
- git clone --depth=50 https://github.com/MATPOWER/matpower.git $TRAVIS_BUILD_DIR/matpower
- rm '/usr/local/include/c++'
- brew update
- brew install ipopt
- brew install octave

env:
  global:
  - IPOPT_VER=3.12.13
  - SEARCH_PATH=$TRAVIS_BUILD_DIR/matpower
#   - MATPOWER_PATH=$TRAVIS_BUILD_DIR/matpower/lib:$TRAVIS_BUILD_DIR/matpower/data:$TRAVIS_BUILD_DIR/matpower/lib/t
#   - SEARCH_PATH=$MOST_PATH:$MPTEST_PATH:$MIPS_PATH:$MATPOWER_PATH

script:
- mkdir $TRAVIS_BUILD_DIR/build
- curl -SL https://www.coin-or.org/download/source/Ipopt/Ipopt-${IPOPT_VER}.tgz | tar -xzC $TRAVIS_BUILD_DIR/build
- mv $TRAVIS_BUILD_DIR/build/Ipopt-${IPOPT_VER}/Ipopt/contrib/MatlabInterface $TRAVIS_BUILD_DIR/build/ipopt
- mv $TRAVIS_BUILD_DIR/matpower/.travis/Makefile $TRAVIS_BUILD_DIR/build/ipopt/src
- make -C $TRAVIS_BUILD_DIR/build/ipopt/src
- mv $TRAVIS_BUILD_DIR/build/ipopt/src/*.mex $TRAVIS_BUILD_DIR/build/ipopt/

- octave-cli --no-gui --eval ver
- octave-cli --no-gui --eval "addpath('$TRAVIS_BUILD_DIR/build/ipopt'); savepath"
- octave-cli --no-gui -p $SEARCH_PATH --eval "install_matpower(1,1,1)"
- octave-cli --no-gui --eval mpver
- octave-cli --no-gui --eval "qps_glpk( [],[1; 1],[1 1],[2],[2],[1; 1],[1; 1],[1; 1],struct('verbose', 3));"
- octave-cli --no-gui --eval "qps_ipopt([],[1; 1],[1 1],[2],[2],[1; 1],[1; 1],[1; 1],struct('verbose', 2));"
