name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-16.04

    steps: 
    - uses: actions/checkout@v1
    - name: Install GNU Octave
      run: |
        sudo add-apt-repository ppa:octave/stable
        sudo apt-get update -qq
        sudo apt-get install -y -qq coinor-libipopt-dev liboctave-dev octave
    - name: Clone MATPOWER
        git clone --depth=50 https://github.com/MATPOWER/matpower.git $HOME/matpower
    - name: Install IPOPT MEX interface
      env:
        IPOPT_VER: 3.11.9
      run: |
        mkdir $HOME/build
        curl -SL https://www.coin-or.org/download/source/Ipopt/Ipopt-${IPOPT_VER}.tgz | tar -xzC $HOME/build
        mv $HOME/build/Ipopt-${IPOPT_VER}/Ipopt/contrib/MatlabInterface $HOME/build/ipopt
        mv $GITHUB_WORKSPACE/.travis/Makefile $HOME/build/ipopt/src
        make -C $HOME/build/ipopt/src
        mv $HOME/build/ipopt/src/*.mex $HOME/build/ipopt/
    - name: Install MATPOWER
      run: |
        octave-cli --no-gui --eval ver
        octave-cli --no-gui --eval "addpath('$HOME/build/ipopt'); savepath"
        octave-cli --no-gui -p $HOME/matpower --eval "install_matpower(1,1,1)"
        octave-cli --no-gui --eval mpver
    - name: Print GLPK and IPOPT version numbers
      run: |
        octave-cli --no-gui --eval "qps_glpk( [],[1; 1],[1 1],[2],[2],[1; 1],[1; 1],[1; 1],struct('verbose', 3));"
        octave-cli --no-gui --eval "qps_ipopt([],[1; 1],[1 1],[2],[2],[1; 1],[1; 1],[1; 1],struct('verbose', 2));"
    - name: Test MP-Test
      run: octave-cli --no-gui --eval "test_mptest(0,1)"
    - name: Test MIPS
      run: octave-cli --no-gui --eval "test_mips(0,1)"
    - name: Test MATPOWER
      run: octave-cli --no-gui --eval "test_matpower(0,1)"
    - name: Test MOST
      run: octave-cli --no-gui --eval "test_most(0,1)"
