name: CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-16.04]

    runs-on: ${{ matrix.os }}

    steps: 
    - uses: actions/checkout@v1
    - name: Install GNU Octave (Linux)
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        sudo add-apt-repository ppa:octave/stable
        sudo apt-get update -qq
        sudo apt-get install -y -qq coinor-libipopt-dev liboctave-dev octave
    - name: Install GNU Octave (Mac)
      if: startsWith(matrix.os, 'macos')
      run: |
        brew update
        brew install pkg-config
        brew install ipopt
        brew install octave
    - name: Clone MATPOWER
      run: git clone --depth=50 https://github.com/MATPOWER/matpower.git $HOME/matpower
    - name: Build IPOPT MEX interface
      env:
        IPOPT_VER: 3.11.9
      run: |
        mkdir $HOME/build
        curl -SL https://www.coin-or.org/download/source/Ipopt/Ipopt-${IPOPT_VER}.tgz | tar -xzC $HOME/build
        mv $HOME/build/Ipopt-${IPOPT_VER}/Ipopt/contrib/MatlabInterface $HOME/build/ipopt
        mv $HOME/matpower/.travis/Makefile $HOME/build/ipopt/src
        make -C $HOME/build/ipopt/src
        mv $HOME/build/ipopt/src/*.mex $HOME/build/ipopt/
    - name: Install IPOPT MEX interface
#      if: startsWith(matrix.os, 'ubuntu')
      run: |
        octave-cli --no-gui --eval ver
        octave-cli --no-gui --eval "addpath('$HOME/build/ipopt'); savepath"
    - name: Install MATPOWER
      run: |
        octave-cli --no-gui --eval ver
        octave-cli --no-gui -p $HOME/matpower --eval "install_matpower(1,1,1)"
        octave-cli --no-gui --eval mpver
    - name: Print GLPK version number
      run: octave-cli --no-gui --eval "qps_glpk( [],[1; 1],[1 1],[2],[2],[1; 1],[1; 1],[1; 1],struct('verbose', 3));"
    - name: Print IPOPT version number
#      if: startsWith(matrix.os, 'ubuntu')
      run: octave-cli --no-gui --eval "qps_ipopt([],[1; 1],[1 1],[2],[2],[1; 1],[1; 1],[1; 1],struct('verbose', 2));"
    - name: Test MP-Test
      run: octave-cli --no-gui --eval "test_mptest(0,1)"
    - name: Test MIPS
      run: octave-cli --no-gui --eval "test_mips(0,1)"
    - name: Test MATPOWER
      run: octave-cli --no-gui --eval "test_matpower(0,1)"
    - name: Test MOST
      run: octave-cli --no-gui --eval "test_most(0,1)"
