name: CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest]

    runs-on: ${{ matrix.os }}

    steps: 
    - uses: actions/checkout@v1
#     - name: core Homebrew install debugging
#       run: |
#         brew update
#         brew install pkg-config
#         brew install ipopt
#         echo $(brew --prefix ipopt)
#         echo "--ls -l /usr/local/opt/"
#         ls -l /usr/local/opt/
#         echo "--ls -l /usr/local/opt/ipopt/"
#         ls -l /usr/local/opt/ipopt/
#         echo "--cat /usr/local/opt/ipopt/INSTALL_RECEIPT.json"
#         cat /usr/local/opt/ipopt/INSTALL_RECEIPT.json
#         echo "--ls -l /usr/local/opt/ipopt/include/coin/"
#         ls -l /usr/local/opt/ipopt/include/coin
#         echo "--ls -l /usr/local/opt/ipopt/lib/"
#         ls -l /usr/local/opt/ipopt/lib/
#         echo "--ls -l /usr/local/opt/ipopt/share/coin/"
#         ls -l /usr/local/opt/ipopt/share/coin/
#         echo "--ls -l /usr/local/bin/"
#         ls -l /usr/local/bin/
#         /user/local/bin/ipopt /usr/local/Cellar/ipopt/3.12.13_2/Ipopt/test/mytop.nl
#         $(brew --prefix ipopt)/bin/ipopt /usr/local/Cellar/ipopt/3.12.13_2/Ipopt/test/mytop.nl
#     - name: octave-app Homebrew debugging
#       run: |
#         brew tap octave-app/octave-app-blas
#         brew tap octave-app/octave-app-bases
#         brew update
#         brew install pkg-config
#         brew install octave-openblas --without-docs
#         brew install ipopt-openblas
#         ln -s $(brew --prefix octave-openblas)/bin/octave /usr/local/bin/octave
#         ln -s $(brew --prefix octave-openblas)/bin/octave-cli /usr/local/bin/octave-cli
    - name: Build IPOPT from Source
      run: |
        brew update
        brew install pkg-config
        brew install gcc
        brew install bash
        git clone https://www.github.com/coin-or/coinbrew
        cd coinbrew
        ./coinbrew fetch Ipopt:stable/3.12 --no-prompt
        ./coinbrew build Ipopt --prefix=$HOME/install --test --no-prompt
        ./coinbrew install Ipopt
        echo "---ls -l ."
        ls -l .
        echo "---ls -l ./Ipopt"
        ls -l ./Ipopt
        echo "---ls -l ./Ipopt/Ipopt/test"
        ls -l ./Ipopt/Ipopt/test
        echo "---ls -l ./Ipopt/Ipopt/contrib"
        ls -l ./Ipopt/Ipopt/contrib
        echo "---ls -l ./ThirdParty"
        ls -l ./ThirdParty
        echo "---ls -l ./build"
        ls -l ./build
        echo "---ls -l ./build/Ipopt"
        ls -l ./build/Ipopt
        echo "---ls -l $HOME"
        ls -l $HOME
        echo "---ls -l $HOME/install"
        ls -l $HOME/install
        echo "---ls -l $HOME/install/bin"
        ls -l $HOME/install/bin
        echo "---ls -l $HOME/install/include"
        ls -l $HOME/install/include
        echo "---ls -l $HOME/install/include/coin"
        ls -l $HOME/install/include/coin
        echo "---ls -l $HOME/install/lib"
        ls -l $HOME/install/lib
        echo "---ls -l $HOME/install/share"
        ls -l $HOME/install/share
        echo "---$HOME/install/bin/ipopt"
        $HOME/install/bin/ipopt ./Ipopt/Ipopt/test/mytoy.nl
#     - name: Clone MATPOWER
#       run: git clone --depth=50 https://github.com/MATPOWER/matpower.git $HOME/matpower
#     - name: Build IPOPT MEX interface
#       env:
#         IPOPT_VER: 3.12.13
#       run: |
#         mkdir $HOME/build
#         curl -SL https://www.coin-or.org/download/source/Ipopt/Ipopt-${IPOPT_VER}.tgz | tar -xzC $HOME/build
#         mv $HOME/build/Ipopt-${IPOPT_VER}/Ipopt/contrib/MatlabInterface $HOME/build/ipopt
#         mv $HOME/matpower/.travis/Makefile $HOME/build/ipopt/src
#         make -C $HOME/build/ipopt/src
#         mv $HOME/build/ipopt/src/*.mex $HOME/build/ipopt/
#     - name: Install IPOPT MEX interface
#       run: |
#         octave-cli --no-gui --eval ver
#         octave-cli --no-gui --eval "addpath('$HOME/build/ipopt'); savepath"
#     - name: Install MATPOWER
#       run: |
#         octave-cli --no-gui --eval ver
#         octave-cli --no-gui -p $HOME/matpower --eval "install_matpower(1,1,1)"
#         octave-cli --no-gui --eval mpver
#     - name: Print GLPK version number
#       run: octave-cli --no-gui --eval "qps_glpk( [],[1; 1],[1 1],[2],[2],[1; 1],[1; 1],[1; 1],struct('verbose', 3));"
#     - name: Print IPOPT version number
#       run: octave-cli --no-gui --eval "qps_ipopt([],[1; 1],[1 1],[2],[2],[1; 1],[1; 1],[1; 1],struct('verbose', 2));"
